import { json } from '@remix-run/node';
import type { ActionFunctionArgs } from '@remix-run/node';
import { getDb } from '@/db.server';
import { startNewRpcSession, WebRpcError } from '@/lib/omp/rpc/manager';
import { isApprovalMode } from '@/lib/omp/config/access-mode';
import { loadPersistedAccessMode } from '@/lib/omp/config/access-mode.server';
import { RpcCommandError, RpcCommandTimeoutError } from '@/lib/omp/rpc/process';

/** The model-dropdown persists its selection here (actionType 'selectModel');
 *  a spawn that arrives without an explicit provider/modelId falls back to it. */
const SELECTED_MODEL_KEY = 'omp_selected_model';

async function loadPersistedModel(): Promise<{ provider: string; modelId: string } | null> {
  try {
    const db = await getDb();
    const row = await db.get('SELECT value FROM app_settings WHERE key = ?', [SELECTED_MODEL_KEY]);
    if (!row?.value) return null;
    const parsed = JSON.parse(row.value) as { provider?: unknown; modelId?: unknown; id?: unknown };
    const provider = typeof parsed.provider === 'string' ? parsed.provider : undefined;
    const modelId = typeof parsed.modelId === 'string' ? parsed.modelId : (typeof parsed.id === 'string' ? parsed.id : undefined);
    return provider && modelId ? { provider, modelId } : null;
  } catch {
    return null;
  }
}

function newSessionErrorResponse(error: unknown) {
  if (error instanceof WebRpcError) {
    return json({ error: error.message, code: error.code }, { status: 400 });
  }
  if (error instanceof RpcCommandTimeoutError) {
    return json({ error: error.message, code: 'rpc_command_timeout' }, { status: 400 });
  }
  if (error instanceof RpcCommandError) {
    return json({ error: error.message, code: error.code ?? 'rpc_command_failed' }, { status: 400 });
  }
  return json({ error: error instanceof Error ? error.message : String(error) }, { status: 400 });
}

// POST /api/agent/new — spawn a brand-new omp session and send the first
// prompt. Mirrors omp-web's /api/agent/new: the session id is generated by
// omp itself, so the chamber adopts it via the URL param after the response.
export async function action({ request }: ActionFunctionArgs) {
  try {
    const body = await request.json().catch(() => null);
    if (!body || typeof body.type !== 'string' || !body.type.trim()) {
      return json({ error: 'command type is required', code: 'command_type_required' }, { status: 400 });
    }
    const cwd = typeof body.cwd === 'string' && body.cwd.trim() ? body.cwd.trim() : undefined;
    if (!cwd) {
      return json({ error: 'cwd is required', code: 'cwd_required' }, { status: 400 });
    }

    // Trust a client-supplied mode only when valid; else use the persisted pick.
    const accessMode = isApprovalMode(body.accessMode) ? body.accessMode : await loadPersistedAccessMode();
    // startNewRpcSession adopts the prewarmed idle process for this cwd when
    // one exists (fired by the sidebar's New Session click) and otherwise
    // cold-spawns — same contract, minus the boot wait when prewarmed.
    const { session, realSessionId } = await startNewRpcSession(cwd, accessMode);

    const { type, message, images, provider, modelId, thinkingLevel } = body as {
      type: string;
      message?: string;
      images?: { data: string; mimeType: string }[];
      provider?: string;
      modelId?: string;
      thinkingLevel?: string;
    };

    const effectiveModel = provider && modelId ? { provider, modelId } : await loadPersistedModel();
    if (effectiveModel) {
      await session.send({ type: 'set_model', ...effectiveModel }).catch(() => {});
    }
    if (thinkingLevel) {
      await session.send({ type: 'set_thinking_level', level: thinkingLevel }).catch(() => {});
    }

    if (type === 'ensure_session') {
      // Seeded client-side before the JSONL has a model_change entry.
      return json({ success: true, sessionId: realSessionId, model: effectiveModel, data: null });
    }

    if (type === 'prompt') {
      const ack = await session.send({
        type: 'prompt',
        message: message ?? '',
        ...(images?.length ? { images } : {}),
      });
      return json({ success: true, sessionId: realSessionId, data: ack });
    }

    return json({ error: `Unsupported command: ${type}` }, { status: 400 });
  } catch (error) {
    return newSessionErrorResponse(error);
  }
}
