import { json } from '@remix-run/node';
import type { ActionFunctionArgs } from '@remix-run/node';
import { randomUUID } from 'crypto';
import { startRpcSession, WebRpcError } from '@/lib/omp/rpc/manager';
import { RpcCommandError, RpcCommandTimeoutError } from '@/lib/omp/rpc/process';

function newSessionErrorResponse(error: unknown) {
  if (error instanceof WebRpcError) {
    return json({ error: error.message, code: error.code }, { status: 400 });
  }
  if (error instanceof RpcCommandTimeoutError) {
    return json({ error: error.message, code: 'rpc_command_timeout' }, { status: 400 });
  }
  if (error instanceof RpcCommandError) {
    return json({ error: error.message, code: error.code ?? 'rpc_command_failed' }, { status: 400 });
  }
  return json({ error: error instanceof Error ? error.message : String(error) }, { status: 400 });
}

// POST /api/agent/new — spawn a brand-new omp session and send the first
// prompt. Mirrors omp-web's /api/agent/new: the session id is generated by
// omp itself, so the chamber adopts it via the URL param after the response.
export async function action({ request }: ActionFunctionArgs) {
  try {
    const body = await request.json().catch(() => null);
    if (!body || typeof body.type !== 'string' || !body.type.trim()) {
      return json({ error: 'command type is required', code: 'command_type_required' }, { status: 400 });
    }
    const cwd = typeof body.cwd === 'string' && body.cwd.trim() ? body.cwd.trim() : undefined;
    if (!cwd) {
      return json({ error: 'cwd is required', code: 'cwd_required' }, { status: 400 });
    }

    // One-time key: startRpcSession coalesces concurrent callers sharing a
    // key, so a unique key guarantees a fresh session per request.
    const tempKey = `__new__${randomUUID()}`;
    const { session, realSessionId } = await startRpcSession(tempKey, '', cwd);

    const { type, message, images, provider, modelId, thinkingLevel } = body as {
      type: string;
      message?: string;
      images?: { data: string; mimeType: string }[];
      provider?: string;
      modelId?: string;
      thinkingLevel?: string;
    };

    if (provider && modelId) {
      await session.send({ type: 'set_model', provider, modelId }).catch(() => {});
    }
    if (thinkingLevel) {
      await session.send({ type: 'set_thinking_level', level: thinkingLevel }).catch(() => {});
    }

    if (type === 'ensure_session') {
      return json({ success: true, sessionId: realSessionId, data: null });
    }

    if (type === 'prompt') {
      const ack = await session.send({
        type: 'prompt',
        message: message ?? '',
        ...(images?.length ? { images } : {}),
      });
      return json({ success: true, sessionId: realSessionId, data: ack });
    }

    return json({ error: `Unsupported command: ${type}` }, { status: 400 });
  } catch (error) {
    return newSessionErrorResponse(error);
  }
}
