/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Dark palettes ported verbatim from OpenChamber
 * (packages/ui/src/lib/theme/themes/*.json, MIT, commit 5e6675b). Only the
 * values the chamber consumes are carried: surface.background -> canvas,
 * surface.elevated -> paper, surface.foreground -> ink, status.* -> signal
 * colors, primary.base -> accent. Field order is the swatch order.
 *
 * Generated data — re-port rather than hand-editing a color here.
 */

import type { ThemePalette } from '@/shared/types/theme';

export const DARK_PALETTES = [
  {
    id: 'aura-dark',
    name: 'Aura',
    family: 'aura',
    variant: 'dark',
    canvas: '#15141B',
    paper: '#201e2b',
    ink: '#EDECEE',
    error: '#FF6767',
    success: '#61FFCA',
    info: '#82E2FF',
    warning: '#FFCA85',
    meta: '#A277FF',
  },
  {
    id: 'ayu-dark',
    name: 'Ayu',
    family: 'ayu',
    variant: 'dark',
    canvas: '#0F1419',
    paper: '#17202a',
    ink: '#D6DAE0',
    error: '#F58572',
    success: '#78D05C',
    info: '#66C6F1',
    warning: '#E4A75C',
    meta: '#3FB7E3',
  },
  {
    id: 'carbonfox-dark',
    name: 'Carbonfox',
    family: 'carbonfox',
    variant: 'dark',
    canvas: '#161616',
    paper: '#222222',
    ink: '#F2F4F8',
    error: '#FF8389',
    success: '#42BE65',
    info: '#78A9FF',
    warning: '#F1C21B',
    meta: '#33B1FF',
  },
  {
    id: 'catppuccin-dark',
    name: 'Catppuccin',
    family: 'catppuccin',
    variant: 'dark',
    canvas: '#1E1E2E',
    paper: '#282841',
    ink: '#CDD6F4',
    error: '#F38BA8',
    success: '#A6D189',
    info: '#89DCEB',
    warning: '#F4B8E4',
    meta: '#7d8fff',
  },
  {
    id: 'dracula-dark',
    name: 'Dracula',
    family: 'dracula',
    variant: 'dark',
    canvas: '#14151F',
    paper: '#161722',
    ink: '#F8F8F2',
    error: '#FF5555',
    success: '#50FA7B',
    info: '#8BE9FD',
    warning: '#FFB86C',
    meta: '#BD93F9',
  },
  {
    id: 'fields-of-the-shire-dark',
    name: 'Fields of the Shire',
    family: 'fields-of-the-shire',
    variant: 'dark',
    canvas: '#1b1815',
    paper: '#2b2622',
    ink: '#ebe0d1',
    error: '#b34d3b',
    success: '#7f905e',
    info: '#667c8a',
    warning: '#c47a3a',
    meta: '#7a8a5a',
  },
  {
    id: 'flexoki-dark',
    name: 'Flexoki',
    family: 'flexoki',
    variant: 'dark',
    canvas: '#171515',
    paper: '#1c1a19',
    ink: '#CECDC3',
    error: '#D14D41',
    success: '#A0AF54',
    info: '#4385BE',
    warning: '#DA702C',
    meta: '#DA702C',
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox',
    family: 'gruvbox',
    variant: 'dark',
    canvas: '#282828',
    paper: '#25292b',
    ink: '#EBDBB2',
    error: '#FB4934',
    success: '#B8BB26',
    info: '#D3869B',
    warning: '#FABD2F',
    meta: '#83A598',
  },
  {
    id: 'jetbrains-dark',
    name: 'JetBrains',
    family: 'jetbrains',
    variant: 'dark',
    canvas: '#1E1F22',
    paper: '#2B2D30',
    ink: '#DFE1E5',
    error: '#FA6675',
    success: '#57965D',
    info: '#3592C4',
    warning: '#F2C55C',
    meta: '#6796f5',
  },
  {
    id: 'kanagawa-dark',
    name: 'Kanagawa',
    family: 'kanagawa',
    variant: 'dark',
    canvas: '#1F1F28',
    paper: '#2A2A37',
    ink: '#DCD7BA',
    error: '#E82424',
    success: '#98BB6C',
    info: '#7E9CD8',
    warning: '#FF9E3B',
    meta: '#7FB4CA',
  },
  {
    id: 'mono-dark',
    name: 'Mono',
    family: 'mono',
    variant: 'dark',
    canvas: '#000000',
    paper: '#141414',
    ink: '#E5E5E5',
    error: '#666666',
    success: '#E5E5E5',
    info: '#A6A6A6',
    warning: '#999999',
    meta: '#FFFFFF',
  },
  {
    id: 'mono-plus-dark',
    name: 'Mono Plus',
    family: 'mono-plus',
    variant: 'dark',
    canvas: '#000000',
    paper: '#141414',
    ink: '#E5E5E5',
    error: '#9e6a6a',
    success: '#6a8e6a',
    info: '#6a7e9e',
    warning: '#9e8a6a',
    meta: '#a2bee8',
  },
  {
    id: 'monokai-dark',
    name: 'Monokai',
    family: 'monokai',
    variant: 'dark',
    canvas: '#23241E',
    paper: '#21221a',
    ink: '#F8F8F2',
    error: '#F92672',
    success: '#A6E22E',
    info: '#66D9EF',
    warning: '#FD971F',
    meta: '#AE81FF',
  },
  {
    id: 'nightowl-dark',
    name: 'Night Owl',
    family: 'night-owl',
    variant: 'dark',
    canvas: '#011627',
    paper: '#001122',
    ink: '#D6DEEB',
    error: '#EF5350',
    success: '#C5E478',
    info: '#82AAFF',
    warning: '#ECC48D',
    meta: '#82AAFF',
  },
  {
    id: 'nord-dark',
    name: 'Nord',
    family: 'nord',
    variant: 'dark',
    canvas: '#1F2430',
    paper: '#1C202A',
    ink: '#E5E9F0',
    error: '#BF616A',
    success: '#A3BE8C',
    info: '#81A1C1',
    warning: '#D08770',
    meta: '#88C0D0',
  },
  {
    id: 'onedarkpro-dark',
    name: 'One Dark Pro',
    family: 'one-dark-pro',
    variant: 'dark',
    canvas: '#1E222A',
    paper: '#232832',
    ink: '#ABB2BF',
    error: '#E06C75',
    success: '#98C379',
    info: '#56B6C2',
    warning: '#E5C07B',
    meta: '#61AFEF',
  },
  {
    id: 'openchamber-dark',
    name: 'OpenChamber',
    family: 'openchamber',
    variant: 'dark',
    canvas: '#120f0e',
    paper: '#181715',
    ink: '#c9c5ba',
    error: '#da5b4a',
    success: '#76ad4f',
    info: '#479fe6',
    warning: '#c67f13',
    meta: '#da7c47',
  },
  {
    id: 'solarized-dark',
    name: 'Solarized',
    family: 'solarized',
    variant: 'dark',
    canvas: '#001e25',
    paper: '#052832',
    ink: '#93A1A1',
    error: '#DC322F',
    success: '#859900',
    info: '#2AA198',
    warning: '#B58900',
    meta: '#278BD2',
  },
  {
    id: 'tokyonight-dark',
    name: 'Tokyonight',
    family: 'tokyonight',
    variant: 'dark',
    canvas: '#0F111A',
    paper: '#131629',
    ink: '#C0CAF5',
    error: '#F7768E',
    success: '#9ECE6A',
    info: '#7DCFFF',
    warning: '#E0AF68',
    meta: '#7AA2F7',
  },
  {
    id: 'vesper-dark',
    name: 'Vesper',
    family: 'vesper',
    variant: 'dark',
    canvas: '#151515',
    paper: '#242121',
    ink: '#e8e5e5',
    error: '#FF8080',
    success: '#99FFE4',
    info: '#FFC799',
    warning: '#FFC799',
    meta: '#FFC799',
  },
  {
    id: 'vitesse-dark-dark',
    name: 'Vitesse Dark',
    family: 'vitesse',
    variant: 'dark',
    canvas: '#121212',
    paper: '#1a1a1a',
    ink: '#dbd7caee',
    error: '#cb7676',
    success: '#4d9375',
    info: '#6394bf',
    warning: '#d4976c',
    meta: '#4d9375',
  },
] as const satisfies readonly ThemePalette[];
