/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Light palettes ported verbatim from OpenChamber
 * (packages/ui/src/lib/theme/themes/*.json, MIT, commit 5e6675b). Only the
 * values the chamber consumes are carried: surface.background -> canvas,
 * surface.elevated -> paper, surface.foreground -> ink, status.* -> signal
 * colors, primary.base -> accent. Field order is the swatch order.
 *
 * Generated data — re-port rather than hand-editing a color here.
 */

import type { ThemePalette } from '@/shared/types/theme';

export const LIGHT_PALETTES = [
  {
    id: 'aura-light',
    name: 'Aura',
    family: 'aura',
    variant: 'light',
    canvas: '#F5F0FF',
    paper: '#f1ebfb',
    ink: '#2D2640',
    error: '#D94F4F',
    success: '#40BF7A',
    info: '#5BB8D9',
    warning: '#D9A24A',
    meta: '#A277FF',
  },
  {
    id: 'ayu-light',
    name: 'Ayu',
    family: 'ayu',
    variant: 'light',
    canvas: '#FDFAF4',
    paper: '#faf6ed',
    ink: '#394049',
    error: '#E6656A',
    success: '#5FB978',
    info: '#2F9BCE',
    warning: '#EA9F41',
    meta: '#4AA8C8',
  },
  {
    id: 'carbonfox-light',
    name: 'Carbonfox',
    family: 'carbonfox',
    variant: 'light',
    canvas: '#FFFFFF',
    paper: '#f4f4f7',
    ink: '#161616',
    error: '#DA1E28',
    success: '#198038',
    info: '#0043CE',
    warning: '#F1C21B',
    meta: '#0072C3',
  },
  {
    id: 'catppuccin-light',
    name: 'Catppuccin',
    family: 'catppuccin',
    variant: 'light',
    canvas: '#fff6f4',
    paper: '#fbefea',
    ink: '#2e314a',
    error: '#D20F39',
    success: '#40A02B',
    info: '#04A5E5',
    warning: '#DF8E1D',
    meta: '#7287FD',
  },
  {
    id: 'dracula-light',
    name: 'Dracula',
    family: 'dracula',
    variant: 'light',
    canvas: '#F8F8F2',
    paper: '#eeeee5',
    ink: '#1F1F2F',
    error: '#D9536F',
    success: '#2FBF71',
    info: '#1D7FC5',
    warning: '#F7A14D',
    meta: '#7C6BF5',
  },
  {
    id: 'fields-of-the-shire-light',
    name: 'Fields of the Shire',
    family: 'fields-of-the-shire',
    variant: 'light',
    canvas: '#f9f5eb',
    paper: '#fcf9f0',
    ink: '#1a1612',
    error: '#a24d3f',
    success: '#4a6030',
    info: '#3d4f5a',
    warning: '#8c5520',
    meta: '#4a6030',
  },
  {
    id: 'flexoki-light',
    name: 'Flexoki',
    family: 'flexoki',
    variant: 'light',
    canvas: '#fffdf4',
    paper: '#fbfaf2',
    ink: '#100F0F',
    error: '#AF3029',
    success: '#66800B',
    info: '#205EA6',
    warning: '#BC5215',
    meta: '#BC5215',
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox',
    family: 'gruvbox',
    variant: 'light',
    canvas: '#f8f1d5',
    paper: '#efebcd',
    ink: '#3C3836',
    error: '#9D0006',
    success: '#79740E',
    info: '#8F3F71',
    warning: '#B57614',
    meta: '#076678',
  },
  {
    id: 'jetbrains-light',
    name: 'JetBrains',
    family: 'jetbrains',
    variant: 'light',
    canvas: '#FFF',
    paper: '#FFFFFF',
    ink: '#000000',
    error: '#CE0606',
    success: '#077D18',
    info: '#389FD6',
    warning: '#F49810',
    meta: '#195ce3',
  },
  {
    id: 'kanagawa-light',
    name: 'Kanagawa',
    family: 'kanagawa',
    variant: 'light',
    canvas: '#f6f3d6',
    paper: '#eae4bf',
    ink: '#545464',
    error: '#E82424',
    success: '#6F894E',
    info: '#4D699B',
    warning: '#DE9800',
    meta: '#4D699B',
  },
  {
    id: 'mono-light',
    name: 'Mono',
    family: 'mono',
    variant: 'light',
    canvas: '#FFFFFF',
    paper: '#FAFAFA',
    ink: '#1A1A1A',
    error: '#999999',
    success: '#1A1A1A',
    info: '#595959',
    warning: '#666666',
    meta: '#000000',
  },
  {
    id: 'mono-plus-light',
    name: 'Mono Plus',
    family: 'mono-plus',
    variant: 'light',
    canvas: '#FFFFFF',
    paper: '#FAFAFA',
    ink: '#1A1A1A',
    error: '#8a5a5a',
    success: '#5a7a5a',
    info: '#5a6a8a',
    warning: '#8a7a5a',
    meta: '#4a6a9e',
  },
  {
    id: 'monokai-light',
    name: 'Monokai',
    family: 'monokai',
    variant: 'light',
    canvas: '#FDF8EC',
    paper: '#FBF5E8',
    ink: '#292318',
    error: '#E54B4B',
    success: '#4FB54B',
    info: '#2D9AD7',
    warning: '#F1A948',
    meta: '#BF7BFF',
  },
  {
    id: 'nightowl-light',
    name: 'Night Owl',
    family: 'night-owl',
    variant: 'light',
    canvas: '#FBFBFB',
    paper: '#FFFFFF',
    ink: '#403F53',
    error: '#DE3D3B',
    success: '#2AA298',
    info: '#4876D6',
    warning: '#C96765',
    meta: '#4876D6',
  },
  {
    id: 'nord-light',
    name: 'Nord',
    family: 'nord',
    variant: 'light',
    canvas: '#ECEFF4',
    paper: '#e7ebf5',
    ink: '#2E3440',
    error: '#BF616A',
    success: '#8FBCBB',
    info: '#81A1C1',
    warning: '#D08770',
    meta: '#5E81AC',
  },
  {
    id: 'onedarkpro-light',
    name: 'One Dark Pro',
    family: 'one-dark-pro',
    variant: 'light',
    canvas: '#F5F6F8',
    paper: '#f0f5fa',
    ink: '#2B303B',
    error: '#E06C75',
    success: '#4FA66D',
    info: '#61AFEF',
    warning: '#D19A66',
    meta: '#528BFF',
  },
  {
    id: 'openchamber-light',
    name: 'OpenChamber',
    family: 'openchamber',
    variant: 'light',
    canvas: '#fdfcfa',
    paper: '#f8f7f5',
    ink: '#393a34',
    error: '#b7493f',
    success: '#5f8d3d',
    info: '#2d72c4',
    warning: '#8d6c15',
    meta: '#b35017',
  },
  {
    id: 'solarized-light',
    name: 'Solarized',
    family: 'solarized',
    variant: 'light',
    canvas: '#FDF6E3',
    paper: '#FAF3DC',
    ink: '#586E75',
    error: '#DC322F',
    success: '#859900',
    info: '#2AA198',
    warning: '#B58900',
    meta: '#268BD2',
  },
  {
    id: 'tokyonight-light',
    name: 'Tokyonight',
    family: 'tokyonight',
    variant: 'light',
    canvas: '#E1E2E7',
    paper: '#dee0ee',
    ink: '#273153',
    error: '#C94060',
    success: '#587539',
    info: '#007197',
    warning: '#8C6C3E',
    meta: '#2E7DE9',
  },
  {
    id: 'vesper-light',
    name: 'Vesper',
    family: 'vesper',
    variant: 'light',
    canvas: '#FFFFFF',
    paper: '#f6f5f5',
    ink: '#101010',
    error: '#d46868',
    success: '#109b76',
    info: '#62bced',
    warning: '#cb7f40',
    meta: '#a06535',
  },
  {
    id: 'vitesse-light-light',
    name: 'Vitesse Light',
    family: 'vitesse',
    variant: 'light',
    canvas: '#ffffff',
    paper: '#f7f7f7',
    ink: '#2c2c28',
    error: '#ab5959',
    success: '#1e754f',
    info: '#296aa3',
    warning: '#a65e2b',
    meta: '#1c6b48',
  },
] as const satisfies readonly ThemePalette[];
