/** Nama brand/teknologi yang harus dipertahankan casing-nya. */
const OVERRIDES: Record<string, string> = {
  github: 'GitHub',
  openai: 'OpenAI',
  gitlab: 'GitLab',
  sqlite: 'SQLite',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  mongodb: 'MongoDB',
  redis: 'Redis',
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  vercel: 'Vercel',
  bun: 'Bun',
  node: 'Node',
  deno: 'Deno',
  react: 'React',
  vue: 'Vue',
  svelte: 'Svelte',
  angular: 'Angular',
  next: 'Next',
  nuxt: 'Nuxt',
  remix: 'Remix',
  tailwind: 'Tailwind',
  prisma: 'Prisma',
  zod: 'Zod',
  axios: 'Axios',
  express: 'Express',
  fastify: 'Fastify',
  koa: 'Koa',
  hono: 'Hono',
  elysia: 'Elysia',
  drizzle: 'Drizzle',
  kysely: 'Kysely',
  biome: 'Biome',
  oxc: 'Oxc',
  rolldown: 'Rolldown',
  turbopack: 'Turbopack',
  vite: 'Vite',
  webpack: 'Webpack',
  rollup: 'Rollup',
  esbuild: 'Esbuild',
  babel: 'Babel',
  swc: 'SWC',
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  coffeescript: 'CoffeeScript',
  dart: 'Dart',
  kotlin: 'Kotlin',
  swift: 'Swift',
  rust: 'Rust',
  python: 'Python',
  ruby: 'Ruby',
  php: 'PHP',
  perl: 'Perl',
  lua: 'Lua',
  scala: 'Scala',
  haskell: 'Haskell',
  elixir: 'Elixir',
  erlang: 'Erlang',
  clojure: 'Clojure',
  ocaml: 'OCaml',
  zig: 'Zig',
  nim: 'Nim',
  crystal: 'Crystal',
  julia: 'Julia',
  groovy: 'Groovy',
  powershell: 'PowerShell',
  bash: 'Bash',
  zsh: 'Zsh',
  fish: 'Fish',
  grep: 'Grep',
  find: 'Find',
  glob: 'Glob',
  ls: 'Ls',
  cat: 'Cat',
  echo: 'Echo',
  mkdir: 'Mkdir',
  rm: 'Rm',
  cp: 'Cp',
  mv: 'Mv',
  touch: 'Touch',
  chmod: 'Chmod',
  chown: 'Chown',
  sudo: 'Sudo',
  apt: 'Apt',
  brew: 'Brew',
  npm: 'Npm',
  pnpm: 'Pnpm',
  yarn: 'Yarn',
  playwright: 'Playwright',
  cypress: 'Cypress',
  puppeteer: 'Puppeteer',
  selenium: 'Selenium',
  jest: 'Jest',
  vitest: 'Vitest',
  mocha: 'Mocha',
  chai: 'Chai',
  sinon: 'Sinon',
  karma: 'Karma',
  jasmine: 'Jasmine',
  qunit: 'QUnit',
  ava: 'Ava',
  tape: 'Tape',
  lodash: 'Lodash',
  underscore: 'Underscore',
  ramda: 'Ramda',
  rxjs: 'RxJS',
  redux: 'Redux',
  zustand: 'Zustand',
  jotai: 'Jotai',
  recoil: 'Recoil',
  mobx: 'MobX',
  xstate: 'XState',
  framer: 'Framer',
  motion: 'Motion',
  gsap: 'GSAP',
  anime: 'Anime',
  three: 'Three',
  babylon: 'Babylon',
  pixi: 'Pixi',
  phaser: 'Phaser',
  matter: 'Matter',
  planck: 'Planck',
  rapier: 'Rapier',
  cannon: 'Cannon',
  ammo: 'Ammo',
  bullet: 'Bullet',
  box2d: 'Box2D',
  chipmunk: 'Chipmunk',
  verlet: 'Verlet',
  ode: 'ODE',
  physx: 'PhysX',
  havok: 'Havok',
  unity: 'Unity',
  unreal: 'Unreal',
  godot: 'Godot',
  bevy: 'Bevy',
  amethyst: 'Amethyst',
  macroquad: 'Macroquad',
  miniquad: 'Miniquad',
  sdl: 'SDL',
  sfml: 'SFML',
  glfw: 'GLFW',
  opengl: 'OpenGL',
  vulkan: 'Vulkan',
  directx: 'DirectX',
  metal: 'Metal',
  webgpu: 'WebGPU',
  webgl: 'WebGL',
  canvas: 'Canvas',
  webaudio: 'WebAudio',
  webmidi: 'WebMIDI',
  webrtc: 'WebRTC',
  websocket: 'WebSocket',
  sse: 'SSE',
  eventsource: 'EventSource',
  fetch: 'Fetch',
  xhr: 'XHR',
  ky: 'Ky',
  got: 'Got',
  undici: 'Undici',
  superagent: 'Superagent',
  request: 'Request',
  needle: 'Needle',
  bent: 'Bent',
  r2: 'R2',
  s3: 'S3',
  gcs: 'GCS',
  azure: 'Azure',
  blob: 'Blob',
  storage: 'Storage',
  firebase: 'Firebase',
  supabase: 'Supabase',
  pocketbase: 'PocketBase',
  appwrite: 'Appwrite',
  nhost: 'Nhost',
  hasura: 'Hasura',
  graphql: 'GraphQL',
  rest: 'REST',
  grpc: 'gRPC',
  trpc: 'tRPC',
  soap: 'SOAP',
  mqtt: 'MQTT',
  amqp: 'AMQP',
  kafka: 'Kafka',
  rabbitmq: 'RabbitMQ',
  pubsub: 'PubSub',
  nats: 'NATS',
  zeromq: 'ZeroMQ',
  dds: 'DDS',
  coap: 'CoAP',
  ble: 'BLE',
  zigbee: 'Zigbee',
  lora: 'LoRa',
  nbiot: 'NB-IoT',
  lte: 'LTE',
  wifi: 'Wi-Fi',
  ethernet: 'Ethernet',
  usb: 'USB',
  hdmi: 'HDMI',
  displayport: 'DisplayPort',
  thunderbolt: 'Thunderbolt',
  pcie: 'PCIe',
  nvme: 'NVMe',
  sata: 'SATA',
  ddr: 'DDR',
  ecc: 'ECC',
  xmp: 'XMP',
  docsis: 'DOCSIS',
  gpon: 'GPON',
  epon: 'EPON',
  pon: 'PON',
  olt: 'OLT',
  ont: 'ONT',
  onu: 'ONU',
  odn: 'ODN',
  p2mp: 'P2MP',
  p2p: 'P2P',
  ftth: 'FTTH',
  fttb: 'FTTB',
  fttc: 'FTTC',
  fttn: 'FTTN',
  hfc: 'HFC',
  dsl: 'DSL',
  adsl: 'ADSL',
  vdsl: 'VDSL',
  sdsl: 'SDSL',
  shdsl: 'SHDSL',
  isdn: 'ISDN',
  pstn: 'PSTN',
  pots: 'POTS',
  voip: 'VoIP',
  sip: 'SIP',
  rtp: 'RTP',
  rtcp: 'RTCP',
  rtsp: 'RTSP',
  hls: 'HLS',
  dash: 'DASH',
  mpeg: 'MPEG',
  av1: 'AV1',
  vp9: 'VP9',
  vp8: 'VP8',
  hevc: 'HEVC',
  avc: 'AVC',
  mp4: 'MP4',
  mkv: 'MKV',
  avi: 'AVI',
  mov: 'MOV',
  wmv: 'WMV',
  flv: 'FLV',
  webm: 'WebM',
  ogg: 'OGG',
  mp3: 'MP3',
  wav: 'WAV',
  flac: 'FLAC',
  aac: 'AAC',
  midi: 'MIDI',
  opus: 'OPUS',
  alac: 'ALAC',
  ape: 'APE',
  wavpack: 'WavPack',
};

/** Akronim yang selalu uppercase. */
const ACRONYMS = new Set([
  'MCP', 'AST', 'LSP', 'DAP', 'RPC', 'SSH', 'TTS', 'STT', 'URL', 'API',
  'JSON', 'SQL', 'CSS', 'HTML', 'JS', 'TS', 'PDF', 'PR', 'UI', 'UX',
  'DB', 'CLI', 'TUI', 'IDE', 'HTTP', 'HTTPS', 'OAUTH', 'YAML', 'XML',
  'CSV', 'PNG', 'SVG', 'WASM', 'AI', 'ML', 'LLM', 'RAG', 'SDK', 'GUI',
  'DOM', 'ESM', 'CJS', 'UMD', 'IIFE', 'XHR', 'TCP', 'UDP', 'DNS', 'IP',
  'GPU', 'CPU', 'RAM', 'SSD', 'HDD', 'FIFO', 'PTY', 'TTY', 'WEB',
]);

/** Title case nama tool: `web_search` → `Web Search`, `mcp__filesystem_read` → `MCP Filesystem Read`. */
export function toTitleCase(name: string): string {
  if (!name) return name;
  const parts = name.split('__');
  const head = parts.length > 1 ? parts[0] : null;
  const rest = parts[parts.length - 1];
  const words = rest.split(/[_\-\s]+/).filter(Boolean);
  const titled = words
    .map((word) => {
      const lower = word.toLowerCase();
      const override = OVERRIDES[lower];
      if (override) return override;
      const upper = word.toUpperCase();
      if (ACRONYMS.has(upper)) return upper;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
  return head ? `${head.toUpperCase()} ${titled}` : titled;
}
